### ISSUE TITLE
Error handling broke

### ISSUE THREAD

**Issue by amitava82** [azuqua/azuqua.js#17]
Earlier error handling has check for status code to determine error. With recent change it has been removed and broke our product.

For instance, `ContinueIf` card, if condition not met, it returns response like so:
```
{message: "Some message", statusCode: 400}
```
Callback should be called with error. 
```
callback(new Error(response.message), null);

**Comment by quy-le** [comment]
Hi,

After talking with Osmond, we're choosing to stay the course with the current error handling direction in the client.

```javascript
        if (resp.body.error) {
          callback(new Error(resp.body.error.message ? resp.body.error.message : resp.body.error));
        }
        else {
          callback(null, resp.body);
        }
```

The reasoning behind this is that the engine will return a response body with an error property which contains an error object if and only if the engine fails to process the FLO (not when the endpoint of the FLO returns an error, more on this below).

If the endpoint of the FLO returns an error, we want to pass this up to whoever is calling without returning an error object because this tells the client that it wasn't the azuqua engine that failed, it was the endpoint.

@osmondgunarso correct me if I'm wrong.

Quy
